spring:
  datasource:
    url: jdbc:h2:mem:pbsub;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false

# Access H2 Console: http://localhost:8080/h2-console
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

# Swagger UI Configuration - using default paths
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  packages-to-scan: com.phoebe.pbsub.web.api

